apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgscoring-ms
  labels:
    app: bgscoring-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgscoring-ms
  template:
    metadata:
      labels:
        app: bgscoring-ms
    spec:
      containers:
        - name: bgscoring-ms
          image: islamahmad/eaproj-bgscoringms:1.0.1
          env:
            - name: SERVER_PORT
              value: "8080"

            #MONGODB QUESTIONS
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: bgscoring-ms
                  key: MONGODB_PASS

          envFrom:
            - configMapRef:
                name: bgscoring-ms
            - configMapRef:
                name: services-global
            - configMapRef:
                name: kafka-global
